### ISSUE TITLE
Update resources_controller (rc_rails gem) to be Rails 5.x compatible [ ruby, rails ]

### ISSUE THREAD

**Issue by jlsync** [ianwhite/resources_controller#12]
Hi, this is a meta-issue looking for someone to update this gem. 

I've posted a small bounty here 
https://www.bountysource.com/issues/46305651-update-resources_controller-rc_rails-gem-to-be-rails-5-x-compatible  - rails - ruby - gem

# Update rc_rails gem to be Rails 5 compatible

The resources_controller / rc_rails gem by @ianwhite from https://github.com/ianwhite/resources_controller needs to be updated to work with Rails 5.1

Rough todo list:

  1. fork git repository
  
  2. update code. sub tasks include:
  
    - [ ] remove/replace use of `alias_method_chain`, `hide_method` and other deprecated method calls
    - [ ] update to current ActiveRecord finder syntax and methods
    - [ ] update default actions to be compatible with rails' strong paramaters
      - e.g. `self.resource = new_resource self.send("#{resource_name}_params")`
    - [ ] must work with rails 5.1.x with no deprecated method warnings
    - [ ] must work with ruby 2.4.1 with no deprecated method warnings
    - [ ] update tests and rspec version
      - all existing tests need to pass
    - [ ] all existing gem features need to work, inlcuding:
      - deeply nested resources
      - child and/or parent singluar resource when nested
      - route helpers
      - custom methods
      - custom finders
      - `map_enclosing_resource`
      - `resource_path:` in config/routes.rb
    - [ ]  update readme and gem documentation where required
      - e.g. https://github.com/ianwhite/resources_controller/blob/master/lib/resources_controller.rb

3. submit pull request back to this repo
  
*Fake or Spam reponses to this issue will be deleted*

**Comment by jlsync** [comment]
This issue and small bounty, just FYI: Forkers and contributers:  @ianwhite @econsultancy @jemmyw @tomtt @revolutionhealth @sinsoku @rst @e-accent @HomeStayTravel @Alliants @LiquidPlanner @ideeli @vladvinnikov @yyyc514 @aughr @mocoso @tomstuart @reinh @tpope @rst @paolodona 

Please mention/pass-on to anyone who might like to work on this.

**Comment by denim2x** [comment]
@jlsync I think I can pull this off

**Comment by jlsync** [comment]
@denim2x  I notice that your public activity (track record) on github and bountysource is dubious. I doubt we'll see anything from you, let alone a working solution. 

However, if you're serious, yes, please have a go and report back here often on your progress and/or lack thereof  - so as to not unnecessarily deter others from working on this.

**Comment by jlsync** [comment]
This work now has been mostly done. My updates are here https://github.com/jlsync/resources_controller 
It seems to work with Rails 5.0.8, 5.1.1, 5.1.2rc1 okay, and probably 4.2.
I am closing this issue (because it's linked to bountysource.com - please don't reopen).

**Comment by ianwhite** [comment]
Amazing work Jason!
